// Data-driven configuration for every world in the game.
// Journey order: Moon -> Mars -> Mercury -> Venus -> Jupiter -> Saturn ->
// Uranus -> Neptune -> Pluto. Each entry drives the look of the world,
// the missions you complete there, and the real facts you learn.
//
// Mission types:
//   collect - gather N items of `item`
//   reach   - drive to a beacon (set atLandmark to put it on the big landmark)
//   scan    - hold the rover near a feature to scan it
//   drill   - hold over a deposit pad while the drill bores down
//   photo   - line the landmark up in view from a distance and hold steady
// Each mission has a short `brief` (the story / why) and a `science` payoff
// shown when you complete it.

export const PLANETS = [
  {
    id: 'moon',
    name: 'The Moon',
    texture: 'moon.jpg',
    type: 'Natural satellite',
    sky: 0x05060a,
    fog: 0x05060a,
    fogDensity: 0.012,
    light: 0xffffff,
    lightIntensity: 1.5,
    ambient: 0x222533,
    groundTint: 0xbfbfbf,
    gravity: 1.6,
    intro:
      "Earth's only natural satellite. No air, no weather \u2014 just 4.5 billion " +
      'years of dust and craters. A great place to test your new rover!',
    facts: [
      'The Moon has no atmosphere, so footprints from 1969 are still there today.',
      'Gravity is only 1/6th of Earth\u2019s \u2014 you could jump six times higher.',
      'Those grey plains are called "maria" \u2014 Latin for seas \u2014 but they are dried lava, not water.',
    ],
    missions: [
      { id: 'moon-rocks', type: 'collect', item: 'rock', count: 8, color: 0x9a9a9a,
        label: 'Collect 8 Moon rocks',
        brief: 'Geologists want fresh samples from the lunar maria to date the lava flows.',
        science: 'Apollo astronauts brought back 382 kg of Moon rocks. They taught us the Moon formed from debris after a Mars-sized world hit the young Earth.' },
      { id: 'moon-scan', type: 'scan',
        label: 'Scan the shadowed crater rim',
        brief: 'Park by the crater wall and let the spectrometer read the icy shadows.',
        science: 'Deep craters at the Moon\u2019s poles never see sunlight and trap frozen water \u2014 future astronauts could drink it and split it into rocket fuel.' },
      { id: 'moon-beacon', type: 'reach',
        label: 'Reach the Apollo landing beacon',
        brief: 'Retrace humanity\u2019s first steps and recover the old landing marker.',
        science: 'Lunar dust ("regolith") is razor-sharp because there is no wind or water to smooth it. It wrecked Apollo seals, spacesuits and machinery.' },
    ],
  },
  {
    id: 'mars',
    name: 'Mars',
    texture: 'mars.jpg',
    type: 'Terrestrial planet',
    sky: 0xc9885b,
    fog: 0xc08a63,
    fogDensity: 0.01,
    light: 0xffd9b3,
    lightIntensity: 1.25,
    ambient: 0x4a2e22,
    groundTint: 0xc1572d,
    gravity: 3.7,
    intro:
      'The Red Planet. Cold, rusty deserts, giant volcanoes and dusty skies. ' +
      'Real rovers like Curiosity and Perseverance are exploring here right now.',
    facts: [
      'Mars looks red because its soil is full of iron oxide \u2014 literally rust.',
      'It hosts Olympus Mons, the tallest volcano in the solar system, 3x the height of Mt Everest.',
      'A day on Mars is 24h 37m \u2014 almost the same as Earth.',
    ],
    missions: [
      { id: 'mars-core', type: 'drill',
        label: 'Drill a rock core in the crater floor',
        brief: 'Bore into the ancient lakebed and cache a core tube for sample return.',
        science: 'Perseverance seals rock cores in metal tubes and drops them on the surface for a future mission to fly back to Earth \u2014 the first Mars sample return.' },
      { id: 'mars-ice', type: 'collect', item: 'ice', count: 6, color: 0xbfe3ff,
        label: 'Collect 6 buried ice cores',
        brief: 'Subsurface radar pinged buried ice. Dig out samples before they sublimate.',
        science: 'Mars hides enormous amounts of water ice underground and at its poles. Melted, it could cover the whole planet in an ocean metres deep.' },
      { id: 'mars-volcano', type: 'photo', atLandmark: true,
        label: 'Photograph the giant volcano',
        subject: 'Olympus Mons',
        brief: 'Back off and frame the towering shield volcano on the horizon for orbit.',
        science: 'Olympus Mons is 22 km tall and as wide as France. Low gravity and a still crust let Martian volcanoes grow into giants.' },
    ],
  },
  {
    id: 'mercury',
    name: 'Mercury',
    texture: 'mercury.jpg',
    type: 'Terrestrial planet',
    sky: 0x070707,
    fog: 0x141414,
    fogDensity: 0.008,
    light: 0xffffff,
    lightIntensity: 2.2,
    ambient: 0x202020,
    groundTint: 0x9c9088,
    gravity: 3.7,
    intro:
      'The smallest planet and the closest to the Sun. Scorching by day, ' +
      'freezing by night, and covered in craters like the Moon.',
    facts: [
      'Mercury swings from +430\u00b0C in sunlight to \u2212180\u00b0C in shadow \u2014 the biggest temperature range of any planet.',
      'It has almost no atmosphere to trap heat, so nights are brutally cold.',
      'A year on Mercury is just 88 Earth days \u2014 it races around the Sun.',
    ],
    missions: [
      { id: 'merc-metal', type: 'collect', item: 'metal', count: 9, color: 0xb8a07a,
        label: 'Collect 9 metal-rich rocks',
        brief: 'Sample the iron-laden crust to weigh Mercury\u2019s oversized core.',
        science: 'Mercury\u2019s giant iron core fills about 60% of its volume \u2014 it is the most metallic planet, perhaps a survivor of a colossal early collision.' },
      { id: 'merc-scan', type: 'scan',
        label: 'Scan a permanently shadowed crater',
        brief: 'Even here, dark crater floors may hide ice. Hold position and scan.',
        science: 'This close to the Sun, permanently shadowed polar craters still hold frozen water ice that never gets warmed by sunlight.' },
      { id: 'merc-scarp', type: 'reach', atLandmark: true,
        label: 'Climb to the giant cliff (scarp)',
        brief: 'Drive up the kilometres-high wrinkle ridge to plant a survey beacon.',
        science: 'Mercury is shrinking! As its iron core slowly cools it contracts, buckling the crust into cliffs called "lobate scarps".' },
    ],
  },
  {
    id: 'venus',
    name: 'Venus',
    texture: 'venus.jpg',
    type: 'Terrestrial planet',
    sky: 0xe7b96b,
    fog: 0xd9a24f,
    fogDensity: 0.02,
    light: 0xfff0c0,
    lightIntensity: 0.9,
    ambient: 0x6b4a1f,
    groundTint: 0xc98f3a,
    gravity: 8.9,
    intro:
      'Earth\u2019s "evil twin". Similar in size, but wrapped in thick toxic ' +
      'clouds and hot enough to melt lead. Your rover\u2019s shielding will be tested!',
    facts: [
      'Venus is the hottest planet at about 465\u00b0C \u2014 hotter than Mercury \u2014 because of a runaway greenhouse effect.',
      'Its air is so thick the surface pressure is like being 900 m underwater on Earth.',
      'Venus spins backwards, and one day there is longer than its whole year.',
    ],
    missions: [
      { id: 'venus-rocks', type: 'collect', item: 'rock', count: 10, color: 0xc98f3a,
        label: 'Collect 10 fresh volcanic rocks',
        brief: 'Grab basalt from a recent lava flow before the heat warps your tools.',
        science: 'Venus has more volcanoes than any other planet, and recent data shows some are still erupting and reshaping the surface today.' },
      { id: 'venus-volcano', type: 'photo', atLandmark: true,
        label: 'Photograph the volcanic dome',
        subject: 'Pancake dome',
        brief: 'Frame the broad pancake volcano through the haze for the orbiter.',
        science: 'Thick atmosphere and high pressure squeeze Venus\u2019s lava into wide, flat "pancake domes" found nowhere else in the solar system.' },
      { id: 'venus-beacon', type: 'reach',
        label: 'Reach the crushed lander beacon',
        brief: 'Recover data from a probe that died on the surface decades ago.',
        science: 'The longest any lander survived on Venus was about 2 hours (Soviet Venera 13) before the heat and pressure destroyed it.' },
    ],
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    texture: 'jupiter.jpg',
    type: 'Gas giant',
    sky: 0xd8b48c,
    fog: 0xc8a079,
    fogDensity: 0.025,
    light: 0xfff2dd,
    lightIntensity: 1.1,
    ambient: 0x5a4633,
    groundTint: 0xd8b48c,
    gravity: 24.8,
    intro:
      'The king of the planets \u2014 a giant ball of gas with no solid ground. ' +
      'You\u2019re driving a floating research platform above its swirling clouds.',
    facts: [
      'Jupiter is so big that all the other planets could fit inside it.',
      'It has no real surface \u2014 it is mostly hydrogen and helium gas that thickens into liquid.',
      'The Great Red Spot is a storm bigger than Earth that has raged for centuries.',
    ],
    missions: [
      { id: 'jup-gas', type: 'collect', item: 'gas', count: 12, color: 0xe8c89a,
        label: 'Scoop 12 cloud-gas samples',
        brief: 'Skim the cloud tops to sample the planet\u2019s primordial atmosphere.',
        science: 'Jupiter is mostly hydrogen and helium \u2014 the same stuff as the Sun. With a bit more mass it could have become a second star.' },
      { id: 'jup-scan', type: 'scan',
        label: 'Scan the Great Red Spot\u2019s edge',
        brief: 'Hold steady at the storm\u2019s rim and measure its ferocious winds.',
        science: 'Winds in the Great Red Spot reach 600 km/h. The storm is wider than Earth and has howled for at least 150 years.' },
      { id: 'jup-beacon', type: 'reach',
        label: 'Reach the Europa relay beacon',
        brief: 'Position the platform to relay signals from the icy moon Europa.',
        science: 'Jupiter has 95+ moons. Europa hides a salty ocean beneath its ice that holds more water than all of Earth\u2019s seas \u2014 a top place to hunt for life.' },
    ],
  },
  {
    id: 'saturn',
    name: 'Saturn',
    texture: 'saturn.jpg',
    type: 'Gas giant',
    sky: 0xe6d3a3,
    fog: 0xd8c48f,
    fogDensity: 0.022,
    light: 0xfff6e0,
    lightIntensity: 1.05,
    ambient: 0x5f5436,
    groundTint: 0xe6d3a3,
    gravity: 10.4,
    intro:
      'The jewel of the solar system, famous for its dazzling rings. ' +
      'Another gas giant \u2014 explore from a platform among the clouds.',
    facts: [
      'Saturn\u2019s rings are made of billions of chunks of ice and rock, from dust grains to house-sized boulders.',
      'Saturn is so light it would float in a giant bathtub of water.',
      'Its rings are wide but incredibly thin \u2014 only about 10 metres thick in places.',
    ],
    missions: [
      { id: 'sat-ice', type: 'collect', item: 'ice', count: 12, color: 0xdff0ff,
        label: 'Collect 12 ring-ice chunks',
        brief: 'Net icy debris drifting down from the rings to study their make-up.',
        science: 'Saturn\u2019s rings are 99% water ice, which is why they shine so brightly. They may be remnants of a shattered moon or comet.' },
      { id: 'sat-scan', type: 'scan',
        label: 'Scan the north-pole hexagon storm',
        brief: 'Align with the strange six-sided jet stream and record its shape.',
        science: 'A bizarre six-sided jet stream \u2014 the "hexagon" \u2014 circles Saturn\u2019s north pole, wide enough to fit four Earths inside it.' },
      { id: 'sat-beacon', type: 'reach',
        label: 'Reach the Titan relay beacon',
        brief: 'Set up a link toward Titan, Saturn\u2019s strange smog-wrapped moon.',
        science: 'Titan has rivers and lakes of liquid methane, a thick orange atmosphere, and is the only moon with weather and a proper surface to land on.' },
    ],
  },
  {
    id: 'uranus',
    name: 'Uranus',
    texture: 'uranus.jpg',
    type: 'Ice giant',
    sky: 0x9fe6e6,
    fog: 0x8fd9da,
    fogDensity: 0.02,
    light: 0xe6ffff,
    lightIntensity: 0.95,
    ambient: 0x2f5a5a,
    groundTint: 0x9fe6e6,
    gravity: 8.7,
    intro:
      'A pale blue-green ice giant that spins on its side. Freezing cold ' +
      'and made largely of icy slush deep below the clouds.',
    facts: [
      'Uranus is tipped over 90\u00b0, so it rolls around the Sun on its side like a ball.',
      'Its blue-green colour comes from methane gas, which absorbs red light.',
      'It is the coldest planet, dropping to around \u2212224\u00b0C.',
    ],
    missions: [
      { id: 'ura-ice', type: 'collect', item: 'ice', count: 10, color: 0xc4f5f5,
        label: 'Collect 10 methane-ice samples',
        brief: 'Sample the frozen slush that gives this world its eerie colour.',
        science: 'Uranus is an "ice giant": below its clouds is a hot, dense slush of water, ammonia and methane. Methane gas is what paints it blue-green.' },
      { id: 'ura-drill', type: 'drill',
        label: 'Drill into the frozen crust',
        brief: 'Bore through the surface ice to read temperatures far below.',
        science: 'Because Uranus is tipped on its side, each pole gets 42 years of constant sunlight followed by 42 years of total darkness.' },
      { id: 'ura-mountain', type: 'photo', atLandmark: true,
        label: 'Photograph the ice peak',
        subject: 'Frozen ice peak',
        brief: 'Frame the towering ridge of ice for the survey archive.',
        science: 'Uranus has 13 faint, dark rings and 28 known moons, all named after characters from Shakespeare and Alexander Pope.' },
    ],
  },
  {
    id: 'neptune',
    name: 'Neptune',
    texture: 'neptune.jpg',
    type: 'Ice giant',
    sky: 0x3a5bd9,
    fog: 0x2f4ec0,
    fogDensity: 0.022,
    light: 0xdfe6ff,
    lightIntensity: 0.85,
    ambient: 0x1b2a66,
    groundTint: 0x3a5bd9,
    gravity: 11.2,
    intro:
      'The most distant planet \u2014 a deep blue, windswept ice giant on the ' +
      'cold edge of the solar system, 30 times farther from the Sun than Earth.',
    facts: [
      'Neptune has the fastest winds in the solar system, over 2,000 km/h.',
      'It is so far away that sunlight there is 900 times dimmer than on Earth.',
      'Neptune was found using maths \u2014 astronomers predicted it before they saw it.',
    ],
    missions: [
      { id: 'nep-ice', type: 'collect', item: 'ice', count: 11, color: 0xbcd0ff,
        label: 'Collect 11 deep-ice samples',
        brief: 'Gather pressurised ice to test the "diamond rain" idea.',
        science: 'Deep inside Neptune crushing pressure may squeeze carbon into diamonds \u2014 scientists think it could literally rain diamonds there.' },
      { id: 'nep-mountain', type: 'photo', atLandmark: true,
        label: 'Photograph the ice ridge',
        subject: 'Frozen ice ridge',
        brief: 'Line up the distant ridge under the dim, faraway Sun.',
        science: 'At Neptune the Sun looks like a bright star. Voyager 2 is the only spacecraft ever to visit, flying past in 1989.' },
      { id: 'nep-beacon', type: 'reach',
        label: 'Reach the windstorm beacon',
        brief: 'Push into the gale to recover a probe lost in the fastest winds known.',
        science: 'Neptune\u2019s winds top 2,000 km/h \u2014 five times stronger than the worst hurricanes on Earth \u2014 despite getting almost no heat from the Sun.' },
    ],
  },
  {
    id: 'pluto',
    name: 'Pluto',
    texture: 'pluto.jpg',
    type: 'Dwarf planet',
    sky: 0x0a0a14,
    fog: 0x141422,
    fogDensity: 0.01,
    light: 0xfff4e6,
    lightIntensity: 0.45,
    ambient: 0x2a2030,
    groundTint: 0xcdb79e,
    gravity: 0.62,
    intro:
      'A tiny, icy dwarf planet far out in the Kuiper Belt. It has a famous ' +
      'heart-shaped glacier and gravity so weak you can barely stay on the ground.',
    facts: [
      'Pluto was reclassified from a planet to a "dwarf planet" in 2006.',
      'It is smaller than Earth\u2019s Moon, and so cold (\u2212229\u00b0C) that nitrogen freezes solid.',
      'Its giant heart-shaped region, Tombaugh Regio, is a glacier of frozen nitrogen.',
    ],
    missions: [
      { id: 'plu-ice', type: 'collect', item: 'ice', count: 9, color: 0xeae0d0,
        label: 'Collect 9 nitrogen-ice samples',
        brief: 'Scoop frozen "air" from the glacier \u2014 gases that are sky on Earth.',
        science: 'Pluto\u2019s surface ice is mostly frozen nitrogen, methane and carbon monoxide \u2014 gases that make up the air we breathe on Earth.' },
      { id: 'plu-heart', type: 'reach', atLandmark: true,
        label: 'Cross onto the heart glacier',
        brief: 'Drive up onto the famous heart-shaped plain of nitrogen ice.',
        science: 'The "heart" of Pluto has glaciers that slowly churn and flow, resurfacing the area so smoothly it has almost no craters.' },
      { id: 'plu-beacon', type: 'photo',
        label: 'Photograph the New Horizons marker',
        subject: 'New Horizons marker',
        brief: 'Frame the marker left where the famous flyby imaged Pluto.',
        science: 'NASA\u2019s New Horizons gave us our first close-up of Pluto in 2015 after a 9-year, 5-billion-km journey across the solar system.' },
    ],
  },
];

// Friendly labels for each collectible item type, used by the HUD.
export const ITEM_LABELS = {
  rock: 'rock',
  ice: 'ice core',
  metal: 'metal rock',
  gas: 'gas sample',
  plasma: 'plasma sample',
};
