// Data-driven configuration for every world in the game.
// Journey order: Moon -> Mars -> Mercury -> Venus -> Jupiter -> Saturn ->
// Uranus -> Neptune -> Pluto -> Sun. Each entry drives the look of the world,
// the missions you complete there, and the real facts you learn.
//
// Colours are plain hex numbers used by THREE.Color.
// `gravity` is surface gravity in m/s^2 (Earth = 9.8) and is used both for the
// rover "feel" and for an on-screen fact.

export const PLANETS = [
  {
    id: 'moon',
    name: 'The Moon',
    texture: 'moon.jpg',
    type: 'Natural satellite',
    sky: 0x05060a,
    fog: 0x05060a,
    fogDensity: 0.012,
    light: 0xffffff,
    lightIntensity: 1.5,
    ambient: 0x222533,
    groundTint: 0xbfbfbf,
    gravity: 1.6,
    intro:
      "Earth's only natural satellite. No air, no weather — just 4.5 billion " +
      'years of dust and craters. A great place to test your new rover!',
    facts: [
      'The Moon has no atmosphere, so footprints from 1969 are still there today.',
      'Gravity is only 1/6th of Earth\u2019s — you could jump six times higher.',
      'Those grey plains are called "maria" — Latin for seas — but they are dried lava, not water.',
    ],
    missions: [
      { id: 'moon-rocks', type: 'collect', item: 'rock', count: 8, color: 0x9a9a9a,
        label: 'Collect 8 Moon rocks',
        fact: 'Apollo astronauts brought back 382 kg of Moon rocks. They taught us the Moon formed from debris after a Mars-sized world hit Earth.' },
      { id: 'moon-beacon', type: 'reach',
        label: 'Drive to the landing beacon',
        fact: 'Lunar dust ("regolith") is razor-sharp because there is no wind or water to smooth it. It wrecks machinery and spacesuits.' },
      { id: 'moon-scan', type: 'scan',
        label: 'Scan the crater rim',
        fact: 'Deep craters at the Moon\u2019s poles never see sunlight and hold frozen water — future astronauts could drink and make fuel from it.' },
    ],
  },
  {
    id: 'mars',
    name: 'Mars',
    texture: 'mars.jpg',
    type: 'Terrestrial planet',
    sky: 0xc9885b,
    fog: 0xc08a63,
    fogDensity: 0.01,
    light: 0xffd9b3,
    lightIntensity: 1.25,
    ambient: 0x4a2e22,
    groundTint: 0xc1572d,
    gravity: 3.7,
    intro:
      'The Red Planet. Cold, rusty deserts, giant volcanoes and dusty skies. ' +
      'Real rovers like Curiosity and Perseverance are exploring here right now.',
    facts: [
      'Mars looks red because its soil is full of iron oxide — literally rust.',
      'It hosts Olympus Mons, the tallest volcano in the solar system, 3x the height of Mt Everest.',
      'A day on Mars is 24h 37m — almost the same as Earth.',
    ],
    missions: [
      { id: 'mars-rocks', type: 'collect', item: 'rock', count: 10, color: 0xb04a25,
        label: 'Collect 10 rock samples',
        fact: 'Perseverance is storing rock samples in tubes for a future mission to bring back to Earth — the first Mars sample return.' },
      { id: 'mars-ice', type: 'collect', item: 'ice', count: 5, color: 0xbfe3ff,
        label: 'Collect 5 buried ice cores',
        fact: 'Mars has huge amounts of water ice at its poles and underground. If melted, it could cover the planet in an ocean metres deep.' },
      { id: 'mars-beacon', type: 'reach',
        label: 'Drive to the canyon beacon',
        fact: 'Valles Marineris is a canyon system as long as the United States and four times deeper than the Grand Canyon.' },
    ],
  },
  {
    id: 'mercury',
    name: 'Mercury',
    texture: 'mercury.jpg',
    type: 'Terrestrial planet',
    sky: 0x070707,
    fog: 0x141414,
    fogDensity: 0.008,
    light: 0xffffff,
    lightIntensity: 2.2,
    ambient: 0x202020,
    groundTint: 0x9c9088,
    gravity: 3.7,
    intro:
      'The smallest planet and the closest to the Sun. Scorching by day, ' +
      'freezing by night, and covered in craters like the Moon.',
    facts: [
      'Mercury swings from +430\u00b0C in sunlight to \u2212180\u00b0C in shadow — the biggest temperature range of any planet.',
      'It has almost no atmosphere to trap heat, so nights are brutally cold.',
      'A year on Mercury is just 88 Earth days — it races around the Sun.',
    ],
    missions: [
      { id: 'merc-metal', type: 'collect', item: 'metal', count: 9, color: 0xb8a07a,
        label: 'Collect 9 metal-rich rocks',
        fact: 'Mercury has a giant iron core that fills about 60% of its volume — it is the most metallic planet.' },
      { id: 'merc-scan', type: 'scan',
        label: 'Scan a shadowed crater',
        fact: 'Even this close to the Sun, permanently shadowed craters near Mercury\u2019s poles contain frozen water ice.' },
      { id: 'merc-beacon', type: 'reach',
        label: 'Reach the cliff (scarp) beacon',
        fact: 'Mercury is shrinking! As its core cools it contracts, wrinkling the surface into cliffs called "scarps".' },
    ],
  },
  {
    id: 'venus',
    name: 'Venus',
    texture: 'venus.jpg',
    type: 'Terrestrial planet',
    sky: 0xe7b96b,
    fog: 0xd9a24f,
    fogDensity: 0.02,
    light: 0xfff0c0,
    lightIntensity: 0.9,
    ambient: 0x6b4a1f,
    groundTint: 0xc98f3a,
    gravity: 8.9,
    intro:
      'Earth\u2019s "evil twin". Similar in size, but wrapped in thick toxic ' +
      'clouds and hot enough to melt lead. Your rover\u2019s shielding will be tested!',
    facts: [
      'Venus is the hottest planet at about 465\u00b0C — hotter than Mercury — because of a runaway greenhouse effect.',
      'Its air is so thick the surface pressure is like being 900 m underwater on Earth.',
      'Venus spins backwards, and one day there is longer than its whole year.',
    ],
    missions: [
      { id: 'venus-rocks', type: 'collect', item: 'rock', count: 10, color: 0xc98f3a,
        label: 'Collect 10 volcanic rocks',
        fact: 'Venus is covered in volcanoes — more than any other planet — and some may still be active today.' },
      { id: 'venus-scan', type: 'scan',
        label: 'Scan the lava plain',
        fact: 'Venus\u2019s surface is young and smooth because lava floods repeatedly repave the whole planet.' },
      { id: 'venus-beacon', type: 'reach',
        label: 'Drive to the probe beacon',
        fact: 'The longest any lander survived on Venus was about 2 hours (Soviet Venera 13) before the heat and pressure destroyed it.' },
    ],
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    texture: 'jupiter.jpg',
    type: 'Gas giant',
    sky: 0xd8b48c,
    fog: 0xc8a079,
    fogDensity: 0.025,
    light: 0xfff2dd,
    lightIntensity: 1.1,
    ambient: 0x5a4633,
    groundTint: 0xd8b48c,
    gravity: 24.8,
    intro:
      'The king of the planets — a giant ball of gas with no solid ground. ' +
      'You\u2019re driving a floating research platform above its swirling clouds.',
    facts: [
      'Jupiter is so big that all the other planets could fit inside it.',
      'It has no real surface — it is mostly hydrogen and helium gas that thickens into liquid.',
      'The Great Red Spot is a storm bigger than Earth that has raged for centuries.',
    ],
    missions: [
      { id: 'jup-gas', type: 'collect', item: 'gas', count: 12, color: 0xe8c89a,
        label: 'Collect 12 cloud-gas samples',
        fact: 'Jupiter is mostly hydrogen and helium — the same stuff as the Sun. It almost became a star itself.' },
      { id: 'jup-scan', type: 'scan',
        label: 'Scan the Great Red Spot',
        fact: 'Winds in the Great Red Spot reach 600 km/h — faster than any storm on Earth.' },
      { id: 'jup-beacon', type: 'reach',
        label: 'Reach the storm-edge beacon',
        fact: 'Jupiter has at least 95 moons. Europa, one of them, hides a salty ocean that might support life.' },
    ],
  },
  {
    id: 'saturn',
    name: 'Saturn',
    texture: 'saturn.jpg',
    type: 'Gas giant',
    sky: 0xe6d3a3,
    fog: 0xd8c48f,
    fogDensity: 0.022,
    light: 0xfff6e0,
    lightIntensity: 1.05,
    ambient: 0x5f5436,
    groundTint: 0xe6d3a3,
    gravity: 10.4,
    intro:
      'The jewel of the solar system, famous for its dazzling rings. ' +
      'Another gas giant — explore from a platform among the clouds.',
    facts: [
      'Saturn\u2019s rings are made of billions of chunks of ice and rock, from dust grains to house-sized boulders.',
      'Saturn is so light it would float in a giant bathtub of water.',
      'Its rings are wide but incredibly thin — only about 10 metres thick in places.',
    ],
    missions: [
      { id: 'sat-ice', type: 'collect', item: 'ice', count: 12, color: 0xdff0ff,
        label: 'Collect 12 ring-ice chunks',
        fact: 'Saturn\u2019s rings are 99% water ice, which is why they shine so brightly in sunlight.' },
      { id: 'sat-scan', type: 'scan',
        label: 'Scan the hexagon storm',
        fact: 'A bizarre six-sided jet stream — the "hexagon" — circles Saturn\u2019s north pole, wide enough to fit four Earths.' },
      { id: 'sat-beacon', type: 'reach',
        label: 'Drive to the ring-shadow beacon',
        fact: 'Saturn has over 140 moons. Titan has lakes of liquid methane and a thick orange atmosphere.' },
    ],
  },
  {
    id: 'uranus',
    name: 'Uranus',
    texture: 'uranus.jpg',
    type: 'Ice giant',
    sky: 0x9fe6e6,
    fog: 0x8fd9da,
    fogDensity: 0.02,
    light: 0xe6ffff,
    lightIntensity: 0.95,
    ambient: 0x2f5a5a,
    groundTint: 0x9fe6e6,
    gravity: 8.7,
    intro:
      'A pale blue-green ice giant that spins on its side. Freezing cold ' +
      'and made largely of icy slush deep below the clouds.',
    facts: [
      'Uranus is tipped over 90\u00b0, so it rolls around the Sun on its side like a ball.',
      'Its blue-green colour comes from methane gas, which absorbs red light.',
      'It is the coldest planet, dropping to around \u2212224\u00b0C.',
    ],
    missions: [
      { id: 'ura-ice', type: 'collect', item: 'ice', count: 11, color: 0xc4f5f5,
        label: 'Collect 11 methane-ice samples',
        fact: 'Uranus is called an "ice giant" because below its clouds is a hot, dense slush of water, ammonia and methane.' },
      { id: 'ura-scan', type: 'scan',
        label: 'Scan the tilted pole',
        fact: 'Because Uranus is tipped on its side, each pole gets 42 years of sunlight followed by 42 years of darkness.' },
      { id: 'ura-beacon', type: 'reach',
        label: 'Reach the faint-ring beacon',
        fact: 'Uranus has 13 dark, narrow rings and was the first planet discovered with a telescope, in 1781.' },
    ],
  },
  {
    id: 'neptune',
    name: 'Neptune',
    texture: 'neptune.jpg',
    type: 'Ice giant',
    sky: 0x3a5bd9,
    fog: 0x2f4ec0,
    fogDensity: 0.022,
    light: 0xdfe6ff,
    lightIntensity: 0.85,
    ambient: 0x1b2a66,
    groundTint: 0x3a5bd9,
    gravity: 11.2,
    intro:
      'The most distant planet — a deep blue, windswept ice giant on the ' +
      'cold edge of the solar system, 30 times farther from the Sun than Earth.',
    facts: [
      'Neptune has the fastest winds in the solar system, over 2,000 km/h.',
      'It is so far away that sunlight there is 900 times dimmer than on Earth.',
      'Neptune was found using maths — astronomers predicted it before they saw it.',
    ],
    missions: [
      { id: 'nep-ice', type: 'collect', item: 'ice', count: 12, color: 0xbcd0ff,
        label: 'Collect 12 deep-ice samples',
        fact: 'Deep inside Neptune the pressure may turn carbon into diamonds — scientists think it could rain diamonds there.' },
      { id: 'nep-scan', type: 'scan',
        label: 'Scan the Great Dark Spot',
        fact: 'Neptune had a storm the size of Earth called the Great Dark Spot — but unlike Jupiter\u2019s, it vanished and reappeared elsewhere.' },
      { id: 'nep-beacon', type: 'reach',
        label: 'Drive to the windstorm beacon',
        fact: 'Voyager 2 is the only spacecraft ever to visit Neptune, flying past it in 1989.' },
    ],
  },
  {
    id: 'pluto',
    name: 'Pluto',
    texture: 'pluto.jpg',
    type: 'Dwarf planet',
    sky: 0x0a0a14,
    fog: 0x141422,
    fogDensity: 0.01,
    light: 0xfff4e6,
    lightIntensity: 0.45,
    ambient: 0x2a2030,
    groundTint: 0xcdb79e,
    gravity: 0.62,
    intro:
      'A tiny, icy dwarf planet far out in the Kuiper Belt. It has a famous ' +
      'heart-shaped glacier and gravity so weak you can barely stay on the ground.',
    facts: [
      'Pluto was reclassified from a planet to a "dwarf planet" in 2006.',
      'It is smaller than Earth\u2019s Moon, and so cold (\u2212229\u00b0C) that nitrogen freezes solid.',
      'Its giant heart-shaped region, Tombaugh Regio, is a glacier of frozen nitrogen.',
    ],
    missions: [
      { id: 'plu-ice', type: 'collect', item: 'ice', count: 9, color: 0xeae0d0,
        label: 'Collect 9 nitrogen-ice samples',
        fact: 'Pluto\u2019s surface ice is mostly frozen nitrogen, methane and carbon monoxide — gases that are air on Earth.' },
      { id: 'plu-scan', type: 'scan',
        label: 'Scan the heart glacier',
        fact: 'The "heart" of Pluto has glaciers that flow and churn, resurfacing the area so it has almost no craters.' },
      { id: 'plu-beacon', type: 'reach',
        label: 'Reach the New Horizons beacon',
        fact: 'NASA\u2019s New Horizons gave us our first close-up of Pluto in 2015 after a 9-year, 5-billion-km journey.' },
    ],
  },
  {
    id: 'sun',
    name: 'The Sun',
    texture: 'sun.jpg',
    type: 'Star',
    sky: 0x1a0500,
    fog: 0x551500,
    fogDensity: 0.02,
    light: 0xffefb0,
    lightIntensity: 2.6,
    ambient: 0x884400,
    groundTint: 0xff7a1a,
    gravity: 274,
    special: 'heat',
    intro:
      'The final mission — the star at the heart of it all. It is blisteringly ' +
      'hot, so watch your HEAT gauge! Park in shade to cool down and grab plasma ' +
      'samples before you overheat.',
    facts: [
      'The Sun is a star — a giant ball of glowing plasma — and contains 99.8% of all mass in the solar system.',
      'Its surface is about 5,500\u00b0C, and its core reaches 15 million\u00b0C.',
      'Light from the Sun takes 8 minutes to reach Earth, travelling 150 million km.',
    ],
    missions: [
      { id: 'sun-plasma', type: 'collect', item: 'plasma', count: 10, color: 0xffd24a,
        label: 'Collect 10 plasma samples',
        fact: 'The Sun fuses 600 million tonnes of hydrogen into helium every second, releasing the energy that lights the solar system.' },
      { id: 'sun-scan', type: 'scan',
        label: 'Scan a solar flare',
        fact: 'Solar flares and coronal mass ejections fling charged particles into space, causing auroras — and sometimes knocking out satellites.' },
      { id: 'sun-beacon', type: 'reach',
        label: 'Reach the Parker Probe beacon',
        fact: 'NASA\u2019s Parker Solar Probe is the fastest object ever built and is the first spacecraft to "touch" the Sun\u2019s outer atmosphere.' },
    ],
  },
];

// Friendly labels for each collectible item type, used by the HUD.
export const ITEM_LABELS = {
  rock: 'rock',
  ice: 'ice core',
  metal: 'metal rock',
  gas: 'gas sample',
  plasma: 'plasma sample',
};
